### ISSUE TITLE
Specifying queue via config file

### ISSUE THREAD

**Issue by andf1** [mbmilligan/batchspawner#10]
Hello --

A second, unrelated issue to my previous ticket. I have not been able to get batchspawner to respect the queue I've specified in jupyterhub_config.py. Here is what I've tried:

<pre><code>c.BatchSpawnerBase.req_queue = 'jupyterhub.q'</code></pre>

and also:

<pre><code>c.GridengineSpawner.batch_script = """#!/bin/bash
  # This wrapper script auto-generated by JupyterHub's BatchSpawner
  #$ -q jupyterhub.q
  #$ -j yes
  #$ -N spawner-jupyterhub
  #$ -v {keepvars}
  #$ {options}
  {cmd}
"""</code></pre>

I got around this by hardcoding the queue in batchspawner/batchspawner.py like so:

<pre><code>[root@wrds-cloud-dev-h batchspawner]# diff batchspawner.orig.py batchspawner.py
454c454
<     batch_submit_cmd = Unicode('sudo -E -u {username} qsub', config=True)
---
>     batch_submit_cmd = Unicode('sudo -i -E -u {username} qsub -q jupyterhub.q', config=True)</code></pre>

(ignore -i flag difference, addressed in my other issue, #9 )

The modification works, but neither config options do. How are you passing these parameters on to Grid Engine? Or am I making an egregious syntax error?

We are running Univa Grid Engine 8.2.1 on Redhat 6, with Jupyterhub 0.7.0-dev

Thanks!

**Comment by mbmilligan** [comment]
Hi! 

I'm not that familiar with Grid Engine, but I am surprised that adding "#$ -q ..." to the job script template did not work. But that may be a quirk of your site configuration, so I'll leave that aside.

For the record, in any of the interpolated strings, you can use "{queue}" to insert the configured value of req_queue. So I would expect the following configuration directives would work:

c.BatchSpawnerBase.req_queue = 'jupyterhub.q'
c.GridengineSpawner.batch_submit_cmd = 'sudo -i -E -u {username} qsub -q {queue}'

**Comment by mbmilligan** [comment]
Resolved with suggestion in #9
